/**
 * The customisation surface, checked structurally.
 *
 * A slot that is declared but never attached to anything is worse than no slot at all: it is
 * a documented promise that silently does nothing, and nobody finds out until they have
 * written the class map. So the first test reads the components and insists that every slot in
 * the public type is actually used somewhere.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

function sources(dir, found = []) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) sources(path, found);
    else if (entry.endsWith(".tsx") || entry.endsWith(".ts")) found.push(path);
  }
  return found;
}

const FILES = sources("src");
const ALL = FILES.map((f) => readFileSync(f, "utf8")).join("\n");
const DECLARED = [
  ...readFileSync("src/editor/customise.tsx", "utf8").matchAll(/^  (\w+)\?: string;/gm),
].map((m) => m[1]);

test("every declared class-name slot is attached to something", () => {
  assert.ok(DECLARED.length >= 10, "the slot list should not have quietly emptied");
  const unused = DECLARED.filter((slot) => {
    // Either passed to the slot helper, or read directly (the root, before the provider).
    const used = new RegExp(`slot\\([^)]*"${slot}"|classNames\\?\\.${slot}`);
    return !used.test(ALL);
  });
  assert.deepEqual(unused, [], `slots declared but never used: ${unused.join(", ")}`);
});

test("no slot is attached that the public type does not declare", () => {
  const used = new Set();
  // Only the arguments of a slot() call — a two-string array anywhere else in the source is
  // just a two-string array.
  for (const call of ALL.matchAll(/slot\(([^)]*)\)/g)) {
    for (const name of call[1].matchAll(/"(\w+)"/g)) used.add(name[1]);
  }
  assert.ok(used.size > 0, "the scan found no slot() calls at all");
  const stray = [...used].filter((slot) => !DECLARED.includes(slot));
  assert.deepEqual(stray, [], `attached but not declared: ${stray.join(", ")}`);
});

test("the base form rule carries no specificity, which is what makes overrides work", () => {
  const css = readFileSync("src/styles.css", "utf8");
  // The rule that used to be six classes deep and beat every component override.
  assert.match(css, /:where\(\.md-root\)\s*\n?\s*:where\(\s*\n?\s*input:not\(/);
  assert.doesNotMatch(
    css,
    /^\.md-root input:not\(\[type="color"\]\)/m,
    "the specificity-heavy form of the base rule must not come back",
  );
});

test("the scoped reset exists, and every part of it is specificity-free", () => {
  const css = readFileSync("src/styles.css", "utf8");
  // `.md-root :where(button)` would be (0,1,0) and would outrank the slot rules below it,
  // which are deliberately weightless. Both halves have to be wrapped.
  assert.doesNotMatch(css, /^\.md-root :where\(/m, "the scope itself must be weightless too");
  for (const element of ["button", "ul, ol", "table", "label"]) {
    assert.match(
      css,
      new RegExp(`:where\\(\\.md-root\\) :where\\([^)]*${element.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`),
      `no reset for ${element} — a host's own rule would bleed through`,
    );
  }
});

test("layout responds to the editor's own width, not the window's", () => {
  const css = readFileSync("src/styles.css", "utf8");
  assert.match(css, /container: md-editor \/ inline-size/);
  assert.match(css, /@container md-editor \(max-width: 900px\)/);
  // A viewport query would be wrong for an embedded widget: the same editor in a narrow panel
  // on a wide page would keep the wide layout.
  assert.doesNotMatch(css, /@media \(max-width: 900px\)/);
});

test("the icon override is generated, not hand-edited into the generated file", () => {
  // icons.tsx is regenerated by scripts/build-icons.mjs, so an edit made there would vanish.
  assert.match(readFileSync("scripts/build-icons.mjs", "utf8"), /useCustomisation\(\)\.icons/);
  assert.match(readFileSync("src/editor/icons.tsx", "utf8"), /useCustomisation\(\)\.icons/);
});

test("!important is not how this file settles arguments with itself", () => {
  // Declarations only: the comments explaining why they are rare would otherwise count.
  const css = readFileSync("src/styles.css", "utf8").replace(/\/\*[\s\S]*?\*\//g, "");
  const count = (css.match(/!important/g) ?? []).length;
  // Whatever is left fights a browser default or a stacked media query, not our own base
  // rules. Asserted so it cannot creep back up unnoticed.
  assert.ok(count <= 21, `!important count rose to ${count}`);
});
